# Generated by Django 4.1.7 on 2023-03-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlearn', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
