# Generated by Django 4.1.7 on 2023-03-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlearn', '0003_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('title4', models.CharField(max_length=200)),
                ('title5', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img')),
                ('image1', models.ImageField(upload_to='img')),
                ('image2', models.ImageField(upload_to='img')),
                ('image3', models.ImageField(upload_to='img')),
                ('image4', models.ImageField(upload_to='img')),
                ('image5', models.ImageField(upload_to='img')),
                ('video', models.FileField(upload_to='video')),
                ('short_des', models.TextField()),
                ('detail_des', models.TextField()),
                ('detail_des1', models.TextField()),
                ('detail_des2', models.TextField()),
                ('detail_des3', models.TextField()),
                ('detail_des4', models.TextField()),
                ('detail_des5', models.TextField()),
            ],
        ),
    ]
