# Generated by Django 4.1.7 on 2023-03-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlearn', '0004_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='video',
        ),
    ]
